In [1]:
a = [1,2,3]
print(a[0])
a[2] = 1
a

1


[1, 2, 1]

In [2]:
import torch

a = torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
# 单个元素仍然是张量
a[1]

tensor(1.)

In [4]:
float(a[1])

1.0

In [5]:
a[2] = 7
a

tensor([1., 1., 7.])

In [6]:
l = [1,1,2,3,4,5]
points = torch.tensor(l)
points

tensor([1, 1, 2, 3, 4, 5])

In [7]:
points = torch.tensor([[1,2.],[3.,4],[5,6]])
points

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [8]:
points.shape

torch.Size([3, 2])

## 三个内存函数

In [9]:
points.storage()

C:\Users\Admin\AppData\Local\Temp\ipykernel_6920\2396954748.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [10]:
sec_point = points[2]
print(sec_point)
# 返回的是第一个元素（5.）在points元素的位置，见上个cell的输出
sec_point.storage_offset()

tensor([5., 6.])


4

In [13]:
print(points.size())
print(points.shape)
print(len(points))

print(sec_point.size())
print(sec_point.shape)
print(len(sec_point))

torch.Size([3, 2])
torch.Size([3, 2])
3
torch.Size([2])
torch.Size([2])
2


In [14]:
sec_point[0] = 10
points

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [10.,  6.]])

In [17]:
another_points = points.clone()
same_points = points
same_points[0][0] = 7
points[0][1] = 8
print(same_points)
print(points)

sec_point[1] = 17
points[0][0] = 27
another_points

tensor([[ 7.,  8.],
        [ 3.,  4.],
        [10., 16.]])
tensor([[ 7.,  8.],
        [ 3.,  4.],
        [10., 16.]])


tensor([[ 7.,  2.],
        [ 3.,  4.],
        [10., 16.]])

In [18]:
sec_point

tensor([10., 17.])

In [20]:
# stride()表示张量内每个维度跳到下个元素所需移动的内存位置数量
print(sec_point.stride())
print(points.stride()) # 第一个维度每个元素有两个数，所以每次移动到下个元素（list）要在内存移动两次

(1,)
(2, 1)
