In [1]:
import torch

In [4]:
points = torch.tensor([[1,2],[3,4],[5,6]], dtype=torch.float32)
points

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [5]:
# 简单说，和numpy一样
points[0,:]

tensor([1., 2.])

In [7]:
points[1:,:]

tensor([[3., 4.],
        [5., 6.]])

In [8]:
points[:,:1]

tensor([[1.],
        [3.],
        [5.]])

In [9]:
# 转换成numpy
points_1 = torch.ones(3,4)
points_np = points_1.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [11]:
points_1 = torch.from_numpy(points_np)
points_1

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
# 存储和读写

# 方式1
torch.save(points_1,'points_1.t')

# 方式2
with open('points_1.t', 'wb') as f:
    torch.save(points_1, f)

In [13]:
p = torch.load("points_1.t")
p

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
with open('points_1.t', 'rb') as f:
    p = torch.load(f)
p

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
! pip install h5py

In [17]:
import h5py

In [35]:
import gc

gc.collect()

# write
points_1 = torch.ones(3,4)

f = h5py.File('points_1.hdf5','w')
datasets = f.create_dataset('coords', data=points_1.numpy()) # coords是数据的名字
f.close()

OSError: Unable to create file (unable to truncate a file which is already open)

In [34]:
# read
f = h5py.File('points_1.hdf5','r')
dset = f['coords']
# dataset = dset.copy()
f.close()
dset

NameError: name 'dataset' is not defined

In [30]:
points = torch.from_numpy(dset[:])
print(points)
f.close()

ValueError: Not a dataset (not a dataset)

In [43]:
# 维度命名
# 注意names指的是每个维度的名字，而非是tensor的名字
points0 = torch.tensor([[1,2],[3,4]],names=['zero','one'])
points0

<ipython-input-43-3086ff7fb7d2>:3: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10/core/TensorImpl.h:1791.)
  points0 = torch.tensor([[1,2],[3,4]],names=['zero','one'])


tensor([[1, 2],
        [3, 4]], names=('zero', 'one'))

In [44]:
img_t = torch.randn(3,4,4)
weights = torch.tensor([0.2,0.7,0.07])
img_t

tensor([[[-0.4445,  0.4265, -0.1511,  1.6807],
         [-1.4150,  0.4205, -0.1041, -1.2807],
         [-1.3295, -0.1962,  0.0729,  0.1571],
         [ 1.0306, -0.3021, -0.8074, -0.0387]],

        [[-0.5792,  0.8577, -0.5338,  0.6260],
         [ 1.0014, -0.0074, -1.8539, -0.1727],
         [-0.6356,  0.3935,  0.1758, -0.6259],
         [ 0.6945,  1.0608, -0.3506,  0.1708]],

        [[ 0.0339,  0.5212,  0.6857, -0.8748],
         [ 0.9668, -1.9185, -0.0335, -1.1421],
         [ 0.8310, -1.0346,  1.1864, -0.0784],
         [-0.5825, -1.4140, -0.0050,  0.7982]]])

In [ ]:
batch_t = torch.randn(2, 3,4,4)