In [1]:
a = [1,2,3]
print(a[0])
a[2] = 1
a

1


[1, 2, 1]

In [2]:
import torch

a = torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
# 单个元素仍然是张量
a[1]

tensor(1.)

In [4]:
float(a[1])

1.0

In [5]:
a[2] = 7
a

tensor([1., 1., 7.])

In [6]:
l = [1,1,2,3,4,5]
points = torch.tensor(l)
points

tensor([1, 1, 2, 3, 4, 5])

In [7]:
points = torch.tensor([[1,2.],[3.,4],[5,6]])
points

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [8]:
points.shape

torch.Size([3, 2])

## 三个内存函数

In [9]:
# 内存地址
points.storage()

<ipython-input-9-2c8c1a84fa09>:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [10]:
sec_point = points[2]
print(sec_point)
# 返回的是第一个元素（5.）在points元素的位置，见上个cell的输出
sec_point.storage_offset()

tensor([5., 6.])


4

In [11]:
print(points.size())
print(points.shape)
print(len(points))

print(sec_point.size())
print(sec_point.shape)
print(len(sec_point))

torch.Size([3, 2])
torch.Size([3, 2])
3
torch.Size([2])
torch.Size([2])
2


In [12]:
sec_point[0] = 10
points

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [10.,  6.]])

In [13]:
another_points = points.clone()
same_points = points
same_points[0][0] = 7
points[0][1] = 8
print(same_points)
print(points)

sec_point[1] = 17
points[0][0] = 27
another_points

tensor([[ 7.,  8.],
        [ 3.,  4.],
        [10.,  6.]])
tensor([[ 7.,  8.],
        [ 3.,  4.],
        [10.,  6.]])


tensor([[ 1.,  2.],
        [ 3.,  4.],
        [10.,  6.]])

In [14]:
sec_point

tensor([10., 17.])

In [15]:
# stride()表示张量内每个维度跳到下个元素所需移动的内存位置数量
# 移动的步数由每个维度在storage()所在位置而定
print(sec_point.stride())
print(points.stride()) # 第一个维度每个元素有两个数，所以每次移动到下个元素（list）要在内存移动两次

(1,)
(2, 1)


In [16]:
# 转置
print("origin points:",points)
points_t = points.t()
print("transposed points:",points_t)

origin points: tensor([[27.,  8.],
        [ 3.,  4.],
        [10., 17.]])
transposed points: tensor([[27.,  3., 10.],
        [ 8.,  4., 17.]])


In [19]:
print(id(points) == id(points_t))
print(points.storage())
print(points_t.storage())
id(points.storage()) == id(points_t.storage())

False
 27.0
 8.0
 3.0
 4.0
 10.0
 17.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
 27.0
 8.0
 3.0
 4.0
 10.0
 17.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]


True

In [20]:
# 元素顺序为storage()位置，27，8，3，4，10，17
# 第一个维度27到8，移动一步
# 第二个维度27到3，移动两步
points_t.stride()

(1, 2)

In [21]:
some_t = torch.ones(3,4,5)
some_t[1][0][0] = 2
some_t

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[2., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [22]:
# 第一维步间隔要走过后两维，所以是4*5
# 第二维步间隔要走过剩下一维，所以是5
# 最后是最里侧list，每次一步
some_t.stride()

(20, 5, 1)

In [23]:
# 二维以上没有t()函数
# 使用transpose函数需指定转置的维度

transpose_t = some_t.transpose(0,2) # 第0和2维转置，shape变为5，4，3
transpose_t.shape

torch.Size([5, 4, 3])

In [24]:
transpose_t.stride()

(1, 5, 20)

In [26]:
# 对比的是是否和storage()函数返回的位置是否一致

print(points.is_contiguous())
points_t.is_contiguous()

True


False