In [1]:
import torch
import numpy as np

In [2]:
import csv
wine_path = "../data/p1ch4/tabular-wine/winequality-white.csv"
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=";",
                         skiprows=1)
wineq_numpy

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [3]:
import pandas as pd

wineq_pd = pd.read_csv(wine_path,dtype=np.float32, delimiter=";")
wineq_pd_values = wineq_pd.values
wineq_pd_values

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [5]:
print(wineq_pd_values.shape)
col_list = list(wineq_pd.columns)
print(type(col_list))
col_list

(4898, 12)
<class 'list'>


['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality']

In [6]:
wineq = torch.from_numpy(wineq_pd_values)
wineq

tensor([[ 7.0000,  0.2700,  0.3600,  ...,  0.4500,  8.8000,  6.0000],
        [ 6.3000,  0.3000,  0.3400,  ...,  0.4900,  9.5000,  6.0000],
        [ 8.1000,  0.2800,  0.4000,  ...,  0.4400, 10.1000,  6.0000],
        ...,
        [ 6.5000,  0.2400,  0.1900,  ...,  0.4600,  9.4000,  6.0000],
        [ 5.5000,  0.2900,  0.3000,  ...,  0.3800, 12.8000,  7.0000],
        [ 6.0000,  0.2100,  0.3800,  ...,  0.3200, 11.8000,  6.0000]])

In [7]:
data = wineq[:,:-1]
print(data.shape)
label = wineq[:,-1]
print(label.shape)

torch.Size([4898, 11])
torch.Size([4898])


In [8]:
target = label.long()
target

tensor([6, 6, 6,  ..., 6, 7, 6])

In [9]:
wineq_pd['quality'].value_counts()

6.0    2198
5.0    1457
7.0     880
8.0     175
4.0     163
3.0      20
9.0       5
Name: quality, dtype: int64

In [12]:
print(target.unsqueeze(1))
print(target.unsqueeze(1).shape)

tensor([[6],
        [6],
        [6],
        ...,
        [6],
        [7],
        [6]])
torch.Size([4898, 1])


In [20]:
import torch
# 创建一个5x5的tensor
t = torch.zeros((5, 5))
# 指定要scatter的位置
index = torch.tensor([[1, 3], [2, 4]])
# 要scatter的值
src = torch.tensor([[9, 8], [7, 6]],dtype=torch.float32)
# 在第1维度上进行scatter
result = torch.scatter(t, 1, index, src)

# 在index tensor 的0行，1，3位置对应改为9，8，第1行的2，4位置修改为7，6
# 具体来说，result中的第0行、第1行、第2行分别对应于index中第0行、第1行、第2行所指定的位置。
# 因此，index中的[1,3]对应于result中的[0,1]和[0,3]，[2,4]对应于result中的[1,2]和[1,4]。
print(result)

tensor([[0., 9., 0., 8., 0.],
        [0., 0., 7., 0., 6.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [14]:
# one-hot示例

# 先准备对应维度的0张量
# 这里注意下，虽然label只有3-9，但因为是按值对应onehot，所以必须要扩展成10维而不是7维
target_onehot = torch.zeros(target.shape[0],10)

# 在target.unsqueeze(1)对应的index上指定值为1
target_onehot.scatter_(1,target.unsqueeze(1),1.0)
target_onehot

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [17]:
print(target_onehot[-3:])
print(target[-3:])

tensor([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])
tensor([6, 7, 6])


In [21]:
# 归一化
data_mean = torch.mean(data, dim=0)
data_std = torch.std(data, dim=0)

data_normalized = (data - data_mean) / data_std
print(data_normalized.shape)
data_normalized

torch.Size([4898, 11])


tensor([[ 1.7208e-01, -8.1761e-02,  2.1326e-01,  ..., -1.2468e+00,
         -3.4915e-01, -1.3930e+00],
        [-6.5743e-01,  2.1587e-01,  4.7997e-02,  ...,  7.3995e-01,
          1.3417e-03, -8.2419e-01],
        [ 1.4756e+00,  1.7450e-02,  5.4378e-01,  ...,  4.7505e-01,
         -4.3677e-01, -3.3663e-01],
        ...,
        [-4.2043e-01, -3.7940e-01, -1.1915e+00,  ..., -1.3130e+00,
         -2.6153e-01, -9.0545e-01],
        [-1.6054e+00,  1.1666e-01, -2.8253e-01,  ...,  1.0049e+00,
         -9.6251e-01,  1.8574e+00],
        [-1.0129e+00, -6.7703e-01,  3.7852e-01,  ...,  4.7505e-01,
         -1.4882e+00,  1.0448e+00]])

In [22]:
# 条件筛选示例
bad_index = target <=3 

bad_data = data[bad_index]
bad_data.shape

torch.Size([20, 11])

In [24]:
# 需要重新划分label，因为不是所有10个onehot都是标签（只有7个）
bad_data = data[target <= 3]
mid_data = data[(target > 3) & (target < 7)] # <1>
good_data = data[target >= 7]

# for i, args in enumerate(zip(col_list, bad_mean, mid_mean, good_mean)):
#     print('{:2} {:20} {:6.2f} {:6.2f} {:6.2f}'.format(i, *args))