In [1]:
import torch
import imageio

In [2]:
path = r"C:\Users\gz395qz\OneDrive - EY CHINA\Trigger\EY files\种树/20210302.png"

img_arr = imageio.imread(path)
img_arr.shape

(3840, 2160, 3)

In [3]:
image = torch.from_numpy(img_arr)
# permute是任意调整维度位置，而transpose只能调换两个维度的位置
image = image.permute(2,0,1)
image.shape

torch.Size([3, 3840, 2160])

In [4]:
# 查看整体亮度

image = image.float()
image.mean()

tensor(133.7351)

In [7]:
# 各个通道的平均值

print(image[0,:,:].mean())
print(image[1,:,:].mean())
print(image[2,:,:].mean())

# 可以看出绿色是主体，RGB通道中，绿色通道平均值最大

tensor(123.4287)
tensor(148.4843)
tensor(129.2923)


In [6]:
print(image.mean(dim=0))
print(image.mean(dim=1))
print(image.mean(dim=2))

print(image.mean(dim=0).shape)
print(image.mean(dim=1).shape)
print(image.mean(dim=2).shape)

tensor([[17.6667, 17.6667, 17.6667,  ..., 17.6667, 17.6667, 17.6667],
        [17.6667, 17.6667, 17.6667,  ..., 17.6667, 17.6667, 17.6667],
        [17.6667, 17.6667, 17.6667,  ..., 17.6667, 17.6667, 17.6667],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]])
tensor([[10.8070, 10.8055, 10.7982,  ..., 11.9138, 11.9102, 11.9102],
        [32.0727, 32.0708, 31.9302,  ..., 32.3352, 32.1930, 32.1932],
        [16.8188, 16.8182, 16.7279,  ..., 17.0357, 16.9424, 16.9424]])
tensor([[ 9.,  9.,  9.,  ...,  0.,  0.,  0.],
        [25., 25., 25.,  ...,  0.,  0.,  0.],
        [19., 19., 19.,  ...,  0.,  0.,  0.]])
torch.Size([3840, 2160])
torch.Size([3, 2160])
torch.Size([3, 3840])
